version: "3"
services: 
  api: 
    command: bash -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000"
    image: sarasshr/python-fastapi
    depends_on:
      - postgres
    ports:
      - 80:8000

      # ^ listens to changes 
    # env_file:
    #   - ./.env
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT={DB_PORT}
      - DB_NAME={DB_NAME}
      - DB_USER={DB_USER}
      - DB_PASSWORD={DB_PASSWORD}
      - JWT_SECRET={JWT_SECRET}
      - TOKEN_EXPIRY_MINUTES={TOKEN_EXPIRY_MINUTES}
      
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD={POSTGRES_PASSWORD}
      - POSTGRES_DB={POSTGRES_DB}
    volumes:
      - fastapi-db:/var/lib/postgresql/data

volumes:
  fastapi-db:
